#!/usr/bin/env python
#
# This file is part of MyPaint.
# Copyright (C) 2007 by Martin Renold <martinxyz@gmx.ch>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

"""
This script does all the platform dependent stuff. Its main task is
to figure out where the python modules are.
"""

import sys, os

# note: some distros use lib64 instead of lib here, should support both somehow...
lib='/lib/mypaint/'
#lib='/lib/python%d.%d/site-packages/mypaint/' % (sys.version_info[0], sys.version_info[1])
pwd=os.getcwd()

scriptdir=os.path.dirname(sys.argv[0])

# script is installed as $prefix/bin. I just need $prefix to continue.
#dir_install=os.path.normpath(os.path.join(pwd,scriptdir)) # ????
dir_install=scriptdir # same, except maybe if scriptdir is relative

if os.path.basename(dir_install) == 'bin':
    prefix=os.path.dirname(dir_install)
    libpath=prefix+'/share/mypaint'
    sys.path.insert(0, prefix + lib)
    #sys.path.insert(0, libpath + '/python')
    sys.path.insert(0, libpath)
else:
    # we are not installed
    prefix=None
    libpath='.'
    # checking for import error below

try: # just for a nice error message
    from lib import mypaintlib
except ImportError, detail:
    print 'ImportError:', detail
    print "\nWe are not correctly installed or compiled!"
    print 'script = "%s"' % sys.argv[0]
    print 'dir_install = "%s"' % dir_install
    print "\nYou need to run 'scons' to compile the C module first.\n"
    if 'cannot import name' in str(detail).lower():
        print "Maybe try 'python mypaint' instead of './mypaint'.\n"
    raise
    #sys.exit(1)

datapath = libpath
if not os.path.isdir(os.path.join(datapath, 'brushes')):
    print 'Default brush collection not found! It should have been here:'
    print datapath
    raise sys.exit(1)

homepath =  os.path.expanduser('~')
if homepath == '~':
    confpath = os.path.join(prefix, 'UserData')
else:
    confpath = os.path.join(homepath, '.mypaint/')

from gui import application
application.main(datapath, confpath)
